name: Download Himawari Images

on:
  workflow_dispatch:
  repository_dispatch:
    types: [schedule-run]

env:
  RESOLUTIONS: "2160,1080"  # 逗号分隔的分辨率列表
  RETENTION_DAYS: 1         # 图片保留天数
  TARGET_BRANCH: "Picture"   # 目标分支名称

jobs:
  download-process-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送分支

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow requests

    - name: Prepare Picture branch
      run: |
        # 配置Git
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # 创建或切换到Picture分支
        if ! git checkout $TARGET_BRANCH 2>/dev/null; then
          git checkout --orphan $TARGET_BRANCH
          git rm -rf .
          echo "# Himawari Images" > README.md
          git add README.md
          git commit -m "Initialize Picture branch"
        fi

    - name: Run download script
      env:
        RESOLUTIONS: ${{ env.RESOLUTIONS }}
        RETENTION_DAYS: ${{ env.RETENTION_DAYS }}
      run: |
        ls -la
        python himawari_downloader.py .

    - name: Commit and push changes
      run: |
        git add .
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update Himawari images $(date -u +'%Y-%m-%d %H:%M')"
          git push origin $TARGET_BRANCH
        fi