name: Fetch Himawari Satellite Images

on:
  workflow_dispatch:
  repository_dispatch:
    types: [schedule-run]



env:
  RESOLUTIONS: ${{ vars.RESOLUTIONS }}  # 在仓库变量中设置，如 "2160,1440"
  KEEP_DAYS: ${{ vars.KEEP_DAYS || 1 }}  # 默认保留1天

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow requests
        # ping -c 4 himawari8.nict.go.jp  # 测试网络连通性
        
    - name: Run image processing
      run: python himawari_downloader.py
      env:
        RESOLUTIONS: ${{ env.RESOLUTIONS }}
        KEEP_DAYS: ${{ env.KEEP_DAYS }}
        
    - name: Commit to Picture branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        
        # 切换到Picture分支（不存在则创建）
        if git show-ref --quiet refs/heads/Picture; then
          git checkout Picture
        else
          git checkout --orphan Picture
          git rm -rf --quiet .
        fi
        
        # 添加新生成的文件（直接复制，不使用移动操作）
        for dir in */; do
          if [ -d "$dir" ]; then
            # 复制目录内容而不是移动目录
            cp -r "$dir"/* .
            # 删除原始目录
            rm -rf "$dir"
          fi
        done
        
        # 添加所有文件
        git add .
        
        # 提交并推送
        git commit -m "Update satellite images: $(date -u +'%Y-%m-%d %H:%M')"
        git push -f origin Picture