name: Fetch Himawari Satellite Images

on:
  workflow_dispatch:
  repository_dispatch:
    types: [schedule-run]

env:
  RESOLUTIONS: ${{ vars.RESOLUTIONS }}  # 在仓库变量中设置，如 "2160,1440"
  KEEP_DAYS: ${{ vars.KEEP_DAYS || 1 }}  # 默认保留1天

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow requests
        
    - name: Run image processing
      run: python himawari_downloader.py
      env:
        RESOLUTIONS: ${{ env.RESOLUTIONS }}
        KEEP_DAYS: ${{ env.KEEP_DAYS }}
        
    - name: Commit to Picture branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        
        # 切换到Picture分支（不存在则创建）
        git checkout -B Picture 2>/dev/null || git checkout --orphan Picture
        git rm -rf .  # 清空当前分支内容
        
        # 添加新生成的文件
        for dir in */; do
          [ -d "$dir" ] && mv "$dir" .
        done
        git add .
        
        # 提交并推送
        git commit -m "Update satellite images: $(date -u +'%Y-%m-%d %H:%M')"
        git push -f origin Picture